name: NaturalPass
version: '8.0'
main: id.naturalsmp.naturalpass.NaturalPass
api-version: '1.21'
author: [ Natural Dev Creative ]
website: https://www.spigotmc.org/resources/battlepass.125992/
softdepend: [PlaceholderAPI, MythicMobs]

libraries:
  - com.zaxxer:HikariCP:5.1.0
  - com.mysql:mysql-connector-j:8.3.0
  - org.slf4j:slf4j-api:2.0.9
  - org.slf4j:slf4j-simple:2.0.9

commands:
  naturalpass:
    description: Open the NaturalPass GUI or manage battle pass system
    usage: /naturalpass [help|reload|addpremium|removepremium|addxp|removexp|addcoins|removecoins] [player] [amount]
    aliases: [np, pass, battlepass]
    permission: naturalpass.use
    permission-message: You don't have permission to use this command!

permissions:
  naturalpass.use:
    description: Allows use of /naturalpass command
    default: true
  NaturalPass.admin:
    description: Access to admin commands (reload, addpremium, removepremium)
    default: op